### ISSUE TITLE
Stops reading Audio after a Few seconds

### ISSUE THREAD

**Issue by Mdleal** [engineertype/MSGEQ7_MOSFET#1]
I am running one of your MSGEQ7+MOSFET breakout board with an esp8266 nodemcu using the example. After a few seconds the LEDs turn off. I put Serial.println(volumeInBand[i]); in the for loop and only getting back 0's with a few 1's. Ideas? I have tried 2 different audio sources.

Thank you

**Comment by engineertype** [comment]
It sounds like you aren't using an analog pin for MSGEQ7_ANALOG_PIN.

Peter

**Comment by Mdleal** [comment]
It's set to A0. The esp8266 only has one analog pin. I did noticed numbers greater then 1 in the output so there must be something going wrong. I'll try a uno tonight.

**Comment by Mdleal** [comment]
Works with an uno. Seems to be a bug on the nodemcu with reading analog while wifi is enabled.
